{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.metrics.serviceMonitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      relabelings:
        {{- if .Values.metrics.serviceMonitor.relabelings }}
        {{- toYaml .Values.metrics.serviceMonitor.relabelings | nindent 8 }}
        {{- else }}
        - targetLabel: instance
          replacement: {{ .Values.fullnameOverride }}
        {{- end }}
{{- end }}
