FROM golang:1.25.5 AS golang

FROM ubuntu:noble AS build-env

ENV SNOOPY_VERSION=v0.3.5

COPY --from=golang /usr/local/go /usr/local/go
# COPY --from=kubectl /usr/local/bin/kubectl /usr/local/bin/kubectl

RUN mkdir /go
ENV GOPATH=/go
ENV PATH=${GOPATH}/bin:/usr/local/go/bin:${PATH}

# Build-time argument for GitHub Token
ARG GITHUB_TOKEN

# Setup system
RUN set -x && \
    apt-get update && \
    apt-get install -y "curl" "jq" "clang" "llvm" "libelf-dev" "libbpf-dev" "git" "linux-headers-generic" "gcc" "libc6-dev" "make" "cmake" "libpcap-dev" "binutils" "build-essential" "binutils-gold" "iproute2" "lsb-release" "sudo" "ca-certificates" "wget" "just" "libssl-dev"

# Fetch the latest release download URL for the specific architecture
RUN ARCH=$(uname -m) DETECTED_ARCH=$ARCH && \
    case "$ARCH" in \
        "x86_64") ARCH="x86_64";; \
        "aarch64") ARCH="aarch64";; \
        "armv7l") ARCH="armv7";; \
        "ppc64le") ARCH="powerpc64le";; \
        "riscv64") ARCH="riscv64";; \
        *) echo "Unsupported architecture"; exit 1;; \
    esac && \
    echo "Using transformed architecture: $ARCH (detected $DETECTED_ARCH)" && \
    DOWNLOAD_URL=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
    "https://api.github.com/repos/mogenius/snoopy/releases/tags/$SNOOPY_VERSION" | \
    jq -r ".assets[] | select(.name | contains(\"snoopy_$ARCH\")) | .url") && \
    echo "Download URL: $DOWNLOAD_URL" && \
    # Download the binary and move it to /usr/local/bin/snoopy
    curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/octet-stream" $DOWNLOAD_URL -o snoopy && \
    chmod +x snoopy && \
    mv snoopy /usr/local/bin/snoopy

# Install bpftool
RUN set -x && \
    ln -sf /usr/include/asm-generic/ /usr/include/asm && \
    git clone --recurse-submodules https://github.com/libbpf/bpftool.git /opt/bpftool && \
    cd /opt/bpftool/src && \
    make install

RUN echo "Architecture: `uname -m`"
RUN case `uname -m` in \
        x86_64) go install -v github.com/go-delve/delve/cmd/dlv@latest; ;; \
        arm64) go install -v github.com/go-delve/delve/cmd/dlv@latest; ;; \
        aarch64|armv7l|ppc64le|s390x) echo "dlv not supported for this architecture, skipping installation." ;; \
        *) echo "Unsupported architecture, exiting..."; exit 1 ;; \
    esac
RUN go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest
RUN git config --global --add safe.directory "/app"

WORKDIR /app

RUN go version
# RUN kubectl --help
RUN bpftool version

FROM build-env AS builder

LABEL org.opencontainers.image.description="mogenius-k8s-manager"

ENV VERIFY_CHECKSUM=false
ENV CGO_ENABLED=0

ARG GOOS
ARG GOARCH
ARG GOARM

ARG COMMIT_HASH=NOT_SET
ARG GIT_BRANCH=NOT_SET
ARG BUILD_TIMESTAMP=NOT_SET
ARG VERSION=NOT_SET

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go generate ./...
RUN go build -trimpath -gcflags="all=-l" -ldflags="-s -w \
    -X 'mogenius-k8s-manager/src/version.GitCommitHash=${COMMIT_HASH}' \
    -X 'mogenius-k8s-manager/src/version.Branch=${GIT_BRANCH}' \
    -X 'mogenius-k8s-manager/src/version.BuildTimestamp=${BUILD_TIMESTAMP}' \
    -X 'mogenius-k8s-manager/src/version.Ver=$VERSION'" \
    -o "bin/mogenius-k8s-manager" \
    ./src/main.go

FROM ubuntu:noble AS release-image

ARG GOOS
ARG GOARCH
ARG GOARM

ENV GOOS=${GOOS}
ENV GOARCH=${GOARCH}
ENV GOARM=${GOARM}

COPY --from=builder "/app/bin/mogenius-k8s-manager" "/usr/local/bin/mogenius-k8s-manager"
COPY --from=builder "/usr/local/bin/snoopy" "/usr/local/bin/mogenius-snoopy"

RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends "dumb-init" "nfs-common" "ca-certificates" "iproute2" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

# mogenius-k8s-manager release default settings
ENV MO_LOG_LEVEL="warn"

ENTRYPOINT ["dumb-init", "--"]
CMD ["mogenius-k8s-manager", "cluster"]
