apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.mogenius.io
spec:
  group: mogenius.io
  versions:
    - additionalPrinterColumns:
      - name: Display Name
        jsonPath: .spec.displayName
        type: string
      - name: Created By
        jsonPath: .spec.createdBy
        type: string
      - name: Product ID
        jsonPath: .spec.productId
        type: string
      - name: Cluster ID
        jsonPath: .spec.clusterId
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                displayName:
                  type: string
                createdBy:
                  type: string
                productId:
                  type: string
                clusterId:
                  type: string
                gitConnectionId:
                  type: string
                applicationKitRefs:
                  type: array
                  items:
                    type: string
  scope: Cluster
  names:
    plural: projects
    singular: project
    kind: Project
    shortNames:
    - proj
    - pro
    - pj
