apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc11
  namespace: bla
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "openebs-rwx"
  resources:
    requests:
      storage: 1Gi