---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-namespace-pv
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  mountOptions:
    - nolock
  capacity:
    storage: 5Gi
  nfs:
    path: /exports
    server: 123.123.123.123