---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-namespace-pvc
  namespace: nfs-test
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: nfs-namespace-pv