---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-namespace-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    path: /exports
    server: 123.123.123.123