apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: XXX
    namespace: XXX
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi