apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfsnginx-claim1
  namespace: ceph-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs
  volumeMode: Filesystem