apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.mogenius.io
spec:
  group: mogenius.io
  versions:
    - additionalPrinterColumns:
      - name: Cluster
        jsonPath: .spec.cluster.displayName
        type: string
      - name: Project
        jsonPath: .spec.project.displayName
        type: string
      - name: Services
        jsonPath: .spec.serviceCount
        type: integer
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                displayName:
                  type: string
                cluster:
                  type: object
                  properties:
                    name:
                      type: string
                    displayName:
                      type: string
                    description:
                      type: string
                    owner:
                      type: string
                project:
                  type: object
                  properties:
                    name:
                      type: string
                    displayName:
                      type: string
                    description:
                      type: string
                    owner:
                      type: string
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                serviceCount:
                  type: integer
  scope: Namespaced
  names:
    plural: projects
    singular: project
    kind: Project
    shortNames:
    - proj
    - pro
    - pj
