apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  refreshInterval: "15s" # The secrets will be refreshed every 15 seconds
  secretStoreRef:
    name: <SECRET_STORE_NAME> # Reference to the secret store we have created above
    kind: ClusterSecretStore
  target:
    name: <NAME> # K8S secret name
  dataFrom:
    - find:
        path: "<SECRET_FOLDER>"
        name:
          regexp: "<SECRET_NAME>"
      rewrite:
        - regexp:
            source: "<SECRET_FOLDER>/(.*)"
            target: "$1"
