apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: <VAULT_STORE_NAME>
  annotations:
    mogenius-external-secrets/shared-path: <MO_SHARED_PATH_COMBINED>
    mogenius-external-secrets/prefix: <PREFIX>
    mogenius-external-secrets/project-id: <PROJECT_ID>
spec:
  provider:
    vault:
      server: <VAULT_SERVER_URL>
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: <ROLE>
          serviceAccountRef:
            name: <SERVICE_ACC>
            namespace: <MO_DEFAULT_NS>
