apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  refreshInterval: "15s" # The secrets will be refreshed every 15 seconds
  secretStoreRef:
    name: <SECRET_STORE_NAME> # Reference to the secret store we have created above
    kind: ClusterSecretStore
  target:
    name: <NAME> # K8S secret name
  # data:
  #   - secretKey: secrets.json # The key name under which the JSON object will be stored in the Kubernetes Secret
  #     remoteRef:
  #       key: "<MO_SHARED_PATH>"
  #       property: . # This will grab all key-value pairs and store them as a JSON object
  #       conversionStrategy: Default
  #       decodingStrategy: None
  dataFrom:
    - find:
        path: mogenius-external-secrets/data
        name:
          regexp: backend-project
      rewrite:
        - regexp:
            source: "mogenius-external-secrets/data/backend-project"
            target: "$1"
