apiVersion: v1
kind: ConfigMap
metadata:
  name: network-ports-config
  namespace: mogenius
data:
  network-ports: |
    - name: dns-TCP
      port: 53
      protocol: TCP
    - name: dns-UDP
      protocol: UDP
      port: 53
    - name: ftp-control
      protocol: TCP
      port: 21
    - name: ftp
      protocol: TCP
      port: 20
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
    - name: kafka
      protocol: TCP
      port: 9092
    - name: imap
      protocol: TCP
      port: 143
    - name: imap
      protocol: UDP
      port: 220
    - name: idap-TCP
      protocol: TCP
      port: 389
    - name: idap-UDP
      protocol: UDP
      port: 389
    - name: idaps-TCP
      protocol: TCP
      port: 636
    - name: idaps-UDP
      protocol: UDP
      port: 636
    - name: mongodb
      protocol: TCP
      port: 27017
    - name: ms-sql
      protocol: TCP
      port: 1433
    - name: mysql
      protocol: TCP
      port: 3306
    - name: nfs
      protocol: TCP
      port: 111
    - name: ntp
      protocol: UDP
      port: 123
    - name: oracle-db
      protocol: TCP
      port: 1521
    - name: pop3
      protocol: TCP
      port: 110
    - name: postgres
      protocol: TCP
      port: 5432
    - name: redis
      protocol: TCP
      port: 6379
    - name: smtp
      protocol: TCP
      port: 25
    - name: ssh
      protocol: TCP
      port: 22
