name: Build main Image

on:
  push:
    branches:
      - main

jobs:
  build-operator:
    uses: mogenius/github-actions/.github/workflows/build-multiarch.yml@a9d2aeac0610c298cdb23e1c763cdb007284c989 # v1.7.1
    secrets: inherit
    with:
      version: "main"
      image: ghcr.io/mogenius/mogenius-operator
      architectures: amd64,arm64
      push_latest: false
      sign_image: true
      build_args_amd64: |
        GO_BUILDER_IMAGE=ghcr.io/mogenius/go-builder:latest-amd64
        BPFTOOL_IMAGE=ghcr.io/mogenius/bpftool:latest-amd64
      build_args_arm64: |
        GO_BUILDER_IMAGE=ghcr.io/mogenius/go-builder:latest-arm64
        BPFTOOL_IMAGE=ghcr.io/mogenius/bpftool:latest-arm64
