name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    uses: mogenius/github-actions/.github/workflows/go-test.yml@b5293d661baea684bc9d1a95b1ecd64ead344b92 # v1.7.4
    with:
      path: src
  lint:
    uses: mogenius/github-actions/.github/workflows/golangci-lint.yml@b5293d661baea684bc9d1a95b1ecd64ead344b92 # v1.7.4
    with:
      args: --config=.golangci.yml ./src
