name: Helm lint

on:
  push:
    paths:
      - 'helm/**'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
        
      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5

      - name: Run Helm lint
        run: helm lint ./helm/charts/mogenius-operator
